[source]
version = "0.1"
description = "Latent period for COVID-19 infection"
type = "parameter"
location = "data/1.toml"
max_warning = 3
messages = ["3: point estimate",
            "2: equal weight to source materials of varying quality"]
