[source]
version = "0.1"
description = "Mean hospitalisation duration"
type = "parameter"
location = "data/1.toml"
max_warning = 3
messages = ["3: point estimate",
            "2: equal weight to source materials of varying quality"]
hash = "xxx"
