[source]
version = "0.1"
description = "Proportion of population observing social distancing"
type = "distribution"
location = "data/1.toml"
max_warning = 3
messages = ["3: distribution"]
hash = "xxx"
